/* This file is autogenerated from table {table_name}. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : Structure.cst
 * Generator        : {generator} 
 * Date             : {datetime}
 */
 
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace XHS.DataAccess
{
{content}
}
