/* This file is autogenerated. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : DataServiceObjects.cst
 * Generator        : {generator} 
 * Date             : {datetime}
 */
 
using System;
using System.Collections.Generic;

namespace XHS.DataServicesObjects
{
{content}
}
