/* This file is autogenerated from table {table_name}. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : DSC_MakeDSO_FromDBObject.cst
 * Generator        : {generator} 
 * Date             : {datetime}
 */
 
using System;
using XHS.DataAccess;
using XHS.DataServicesObjects;
using XHS.Structures;

namespace XHS.DataServicesConversions
{
  public partial class Conversions
  {
{content}
  }

}
