/* This file is autogenerated from table {table_name}. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : Commands.cst
 * Generator        : {generator} 
 * Date             : {datetime}
 */
 

/****** Object:  StoredProcedure [dbo].[xhs_sp_ins_{table_name_lower}]    Script Date: {datetime} ******/
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[xhs_sp_ins_{table_name_lower}]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[xhs_sp_ins_{table_name_lower}]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xhs_sp_ins_{table_name_lower}] (
	{insert_params},
	@Identity int out
)
AS
BEGIN
    
	INSERT INTO [dbo].[{table_name}]
	(
		{insert_cols}
	)
	VALUES
	(
		{insert_values}
	)
			
	SET @Identity = SCOPE_IDENTITY()
    
END 
GO

/****** Object:  StoredProcedure [dbo].[xhs_sp_upd_{table_name_lower}]    Script Date: {datetime} ******/
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[xhs_sp_upd_{table_name_lower}]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE [dbo].[xhs_sp_upd_{table_name_lower}]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xhs_sp_upd_{table_name_lower}]
	@ID int,
  {insert_params}

AS
BEGIN

	UPDATE [dbo].[{table_name}]
	SET 
		{update_values}  
	WHERE [ID] = @ID

END
GO

/****** Object:  StoredProcedure [dbo].[xhs_sp_del_{table_name_lower}]    Script Date: {datetime} ******/
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[xhs_sp_del_{table_name_lower}]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE [dbo].[xhs_sp_del_{table_name_lower}]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xhs_sp_del_{table_name_lower}]

	@ID int

AS

	DELETE [dbo].[{table_name}]
	WHERE
		[ID] = @ID
GO

/****** Object:  StoredProcedure [dbo].[xhs_sp_get_{table_name_lower}_all]    Script Date: {datetime} ******/
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[xhs_sp_get_{table_name_lower}_all]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[xhs_sp_get_{table_name_lower}_all]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xhs_sp_get_{table_name_lower}_all]

AS

	SELECT t1.*
  FROM [dbo].[{table_name}] as t1
    
GO

/****** Object:  StoredProcedure [dbo].[xhs_sp_get_{table_name_lower}_by_id]    Script Date: {datetime} ******/
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[xhs_sp_get_{table_name_lower}_by_id]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[xhs_sp_get_{table_name_lower}_by_id]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xhs_sp_get_{table_name_lower}_by_id]

	@ID int

AS

	SELECT t1.* 
	FROM [dbo].[{table_name}] as t1
	WHERE
		t1.[ID] = @ID
GO



